### ISSUE TITLE
After logging in, user's name is not displayed

### ISSUE THREAD

**Issue by billfeng** [codechrysalis1/live-jazz#69]
This occurred on local environment.

**Comment by billfeng** [comment]
Screenshot. As you see I appear to be logged in, and the logout button is present, but my name is not there.
<img width="1680" alt="screen shot 2017-09-26 at 9 47 35 am" src="https://user-images.githubusercontent.com/7489794/30837451-12857cb0-a2a0-11e7-8c85-a573bad74229.png">

**Comment by GameKyuubi** [comment]
@bill-feng You might need a .env file.  I'll look into it.
yep, .env.
For future problem-havers: copy all the environment variables from production Heroku **EXCEPT `DATABASE_URL`** into an .env file in your project root, **DO NOT COMMIT THIS FILE**.
